[package]
name = "dendro-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
parking_lot.workspace = true
arc-swap.workspace = true
bytes.workspace = true
sha2.workspace = true
xxhash-rust.workspace = true
crc32c.workspace = true
zstd.workspace = true
serde.workspace = true
serde_json.workspace = true
arrow.workspace = true
sqlparser.workspace = true
tracing.workspace = true
object_store.workspace = true
raft.workspace = true
raft-proto.workspace = true
slog.workspace = true
futures.workspace = true
tokio = { version = "1", features = ["rt-multi-thread"] }
rand.workspace = true

[dev-dependencies]
rand.workspace = true
dendro-columnar = { path = "../dendro-columnar" }
